name: fluent-bit
base: core22
version: '2.0.0'
summary: High performance logs and stream processor
description: |
  Fluent Bit is a high performance log processor and stream processor for Linux.
  It provides a flexible pluggable architecture to collect, enrich and deliver
  logs or metrics to multiple databases or cloud providers.
license: 'Apache-2.0'
icon: fluent-bit.svg
confinement: 'strict'
grade: 'stable'

apps:
  service:
    command: bin/fluent-bit -c $SNAP_COMMON/etc/fluent-bit/fluent-bit.conf
    daemon: simple
    plugs:
      - network
      - network-bind
  fluent-bit:
    command: bin/fluent-bit -c $SNAP_COMMON/etc/fluent-bit/fluent-bit.conf
    plugs:
      - network
      - network-bind

parts:
  fluent-bit:
    source: ./
    plugin: cmake
    stage-packages:
        - libsasl2-2
        - libpq5
    build-packages:
        - g++
        - make
        - libsasl2-dev
        - libsystemd-dev
        - flex
        - bison
        - valgrind
        - libssl-dev
        - libpq5
        - postgresql-server-dev-all
        - libyaml-dev
    cmake-parameters:
        - -DFLB_OUT_KAFKA=On
        - -DFLB_JEMALLOC=On
        - -DFLB_EXAMPLES=Off
        - -DFLB_SHARED_LIB=Off
        - -DFLB_OUT_PGSQL=On
    organize:
      usr/local/bin: bin
      usr/local/etc: etc
      # don't stage unnecessary files
    stage:
      - -lib/systemd
      - -usr/local/include

layout:
  /etc/fluent-bit:
    bind: $SNAP_COMMON/etc/fluent-bit
